name=RCS660S_ESP32
version=0.1.0
author=tarusake
maintainer=tarusake
sentence=Library to control RCS660S
paragraph=Library to control RCS660S
category=Device Control
url=https://github.com/tarusake/RCS660S_ESP32
architectures=*
depends=M5Unified
includes=RCS660S_ESP32.h
